server:
  port: 9011
#  port: 0
spring:
  application:
    name: auth-server
#        namespace: oldguy
  profiles:
    active: ${PROFILES}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update


jwt:
  algorithm: HMACSHA256
  key-name: oldguy-private-key
  expire: 3600

mybatis:
  type-aliases-package: com.example.oldguy.model.dao
  template-location: configs/mapper/mybatis-template.xml
  application-location: D:/workspace/demo/SpringCloudOldguyDemo/oldguy-auth/oldguy-default-auth-server
  mapper-generate-config-location: configs/mapper/mybatis-mapper-generate-config.perporties

mybatis-plus:
  config-location: classpath:configs/myBatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  typeAliasesPackage: com.example.oldguy.model.dao.entities;
