server:
  port: 9013
#  port: 0
spring:
  application:
    name: oldguy-base
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: ${PROFILES}

mybatis:
  type-aliases-package: com.example.oldguy.model.dao.entities.dictionary
  template-location: configs/mapper/mybatis-template.xml
  application-location: D:\workspace\demo\SpringCloudOldguyDemo\oldguy-modules\oldguy-base
  mapper-generate-config-location: configs/mapper/mybatis-mapper-generate-config.perporties

mybatis-plus:
  config-location: classpath:configs/myBatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  typeAliasesPackage: com.example.oldguy.model.dao.entities;
