server:
  port: 9016
#  port: 0
spring:
  application:
    name: oldguy-workflow
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: test
  activiti:
    process-definition-location-prefix: classpath*:/processes/
logging:
  level:
    com.example.oldguy: debug
#    root: debug

mybatis:
  type-aliases-package: com.example.oldguy.model.workflow.dao.entities;com.example.oldguy.model.test.dao.entities;
  template-location: configs/mapper/mybatis-template.xml
  application-location: D:\workspace\demo\SpringCloudOldguyDemo\oldguy-modules\oldguy-workflow
  mapper-generate-config-location: configs/mapper/mybatis-mapper-generate-config.perporties

mybatis-plus:
  config-location: classpath:configs/myBatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
  typeAliasesPackage: com.example.oldguy.model.workflow.dao.entities
  global-config:
    banner: false
    db-config:
      id-type: id_worker_str