test1:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oldguy-demo-multi1?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
test2:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oldguy-demo-multi2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.example.oldguy: debug

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848